// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       throw UnsupportedError(
//         'DefaultFirebaseOptions have not been configured for web - '
//         'you can reconfigure this by running the FlutterFire CLI again.',
//       );
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyD3pDTVqM8Jbv6EPUHmw1xzIZyeWLPtoyg',
//     appId: '1:907583696115:android:23b5eab90699b20eca9b86',
//     messagingSenderId: '907583696115',
//     projectId: 'voicealerts-obs',
//     storageBucket: 'voicealerts-obs.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyD7yue5vm_-7mwSnzXg8rPkpW3eVLxZPKc',
//     appId: '1:907583696115:ios:b6b8af337a533cb6ca9b86',
//     messagingSenderId: '907583696115',
//     projectId: 'voicealerts-obs',
//     storageBucket: 'voicealerts-obs.firebasestorage.app',
//     androidClientId: '907583696115-cgn5q7amu18afcqf6tj93m8kg2okfspp.apps.googleusercontent.com',
//     iosClientId: '907583696115-h1hd4gmje2hbm5lq8bmp2gboc8neriej.apps.googleusercontent.com',
//     iosBundleId: 'com.voicealerts-obs.ios.live',
//   );
// }
